name: Testes Automatizados

on: pull_request

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: "lts/iron"
      - run: npm ci
      - run: npm run lint:prettier:check
