name: Linting

on: pull_request

jobs:
  prettier:
    name: Prettier
    steps:
      - uses: "./.github/workflows/setup.yaml"
      - run: npm run lint:prettier:check

  eslint:
    name: Eslint
    steps:
      - uses: "./.github/workflows/setup.yaml"
      - run: npm run lint:eslint:check
