name: Automated Testing

on: pull_request

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: "lts/iron"
      - run: npm ci
      - run: npm test
